Maleficio para ver errores en el install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+set -eE -o functrace
+
+failure() {
+  local lineno=$1
+  local msg=$2
+  echo "Failed at $lineno: $msg"
+}
+trap 'failure ${LINENO} "$BASH_COMMAND"' ERR
+
+
 cp -r ./lib /usr/local/lib/adlamin
 
 chmod +x ./sbin/*
